### ISSUE TITLE
Compact protocol is encoding floating point numbers incorrectly

### ISSUE THREAD

**Issue by jystic** [abhinav/pinch#15]
The compact protocol is supposed to encode doubles in [little endian](https://github.com/apache/thrift/blob/master/lib/cpp/src/thrift/protocol/TCompactProtocol.tcc#L254-L263) (`THRIFT_htolell` is host to little-endian) but this library is encoding them in [big endian](https://github.com/abhinav/pinch/blob/master/src/Pinch/Protocol/Compact.hs#L255-L257).

**Comment by abhinav** [comment]
Thanks for reporting! Fixing in #16.

**Comment by abhinav** [comment]
Released in 0.3.2.0.
