### ISSUE TITLE
Future Roadmap?

### ISSUE THREAD

**Issue by phile314** [abhinav/pinch#26]
This is really a great library, thank you a lot for creating it :+1: 

Building upon it, I have implemented a code-generator for the pinch library and have a diff to use a streaming parser built on cereal. Would there be interest in merging these changes?

PS: As we are using this library internally, I would also be happy to help with maintenance.

**Comment by abhinav** [comment]
Hello, and thank you for the kind words! Yes, absolutely, a code generator and streaming parser would be most welcome.

That said, I'm not actively maintaining this library anymore so if we merge your code generator, I'd be happy to give you maintainer access to the repository and package publishing permissions on Hackage.

**Comment by phile314** [comment]
Great!

I intend to do a series of pull-requests to the library itself for the streaming parser and some supporting code for the code generator. I am leaning towards putting the code-generator itself into a separate cabal package as it is not needed for compiling/running the generated code.

We have been using all the changes in production for some months now so they are already battle-tested.

**Comment by abhinav** [comment]
That sounds good! I've added you as a collaborator to the GitHub repository and as a maintainer on Hackage.

Thanks!
