### ISSUE TITLE
Allow bytestring 0.12 and deepseq 1.5

### ISSUE THREAD

**Issue by LaurentRDC** [abhinav/pinch#58]
Would it be possible to bump the upper bound on bytestring to `<0.13` and the upper bound on deepseq to `<1.6`

I've been using pinch successfully with the following clause in `cabal.project`:

```
allow-newer: pinch:deepseq
           , pinch:bytestring

**Comment by abhinav** [comment]
@LaurentRDC thanks for the issue! Yes, that's a welcome change if you're willing to make the PR.
I'll tag the release for you after that lands.
