### ISSUE TITLE
network-run-0.3.0 not allowed

### ISSUE THREAD

**Issue by ysangkok** [abhinav/pinch#61]
pinch.cabal prevents this version of network-run. See

* https://github.com/commercialhaskell/stackage/issues/7444

You can enable hackage notifications to get notified when your dependency goes out of bounds:

* https://discourse.haskell.org/t/new-hackage-server-features/2621/38?u=janus

**Comment by abhinav** [comment]
Hey, thanks for the report.
I'm not actively working on this library anymore but I will happily accept PRs.
I've also added two co-maintainers so these PRs won't be blocked on me.
